#!/bin/bash 
tempRaspberry=$(sh ./temp)
tempAmbiente=$(python tempsensor.py)
luminosidad=$(python ldr)
pulsador=$(sh ./valpul) 
echo $tempRaspberry
echo $pulsador
curl -i -XPOST 'https://corlysis.com:8086/write?db=raspberrypi12' -u token:693542bf37490ccfef5f1f33fd9827f0 --data-binary 'tempRaspberry,place=laboratorio value='$tempRaspberry
curl -i -XPOST 'https://corlysis.com:8086/write?db=raspberrypi12' -u token:693542bf37490ccfef5f1f33fd9827f0 --data-binary 'tempAmbiente,place=laboratorio value='$tempAmbiente
curl -i -XPOST 'https://corlysis.com:8086/write?db=raspberrypi12' -u token:693542bf37490ccfef5f1f33fd9827f0 --data-binary 'luminosidad,place=laboratorio value='$luminosidad
curl -i -XPOST 'https://corlysis.com:8086/write?db=raspberrypi12' -u token:693542bf37490ccfef5f1f33fd9827f0 --data-binary 'pulsador,place=laboratorio value='$pulsador
